// <auto-generated />
using System;
using HouseholdFinancialIntelligence.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HouseholdFinancialIntelligence.Infrastructure.Migrations
{
    [DbContext(typeof(HouseholdFinancialDbContext))]
    partial class HouseholdFinancialDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HouseholdFinancialIntelligence.Domain.Aggregates.FinancialMovement.FinancialMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("EvidenceReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FinancialAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "EvidenceReference")
                        .IsUnique()
                        .HasDatabaseName("UX_FinancialMovement_Household_EvidenceReference");

                    b.ToTable("FinancialMovement", (string)null);
                });

            modelBuilder.Entity("HouseholdFinancialIntelligence.Domain.Aggregates.FinancialMovement.FinancialMovement", b =>
                {
                    b.OwnsOne("HouseholdFinancialIntelligence.Domain.SharedKernel.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("FinancialMovementId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("CurrencyCode");

                            b1.HasKey("FinancialMovementId");

                            b1.ToTable("FinancialMovement");

                            b1.WithOwner()
                                .HasForeignKey("FinancialMovementId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
